openapi: 3.0.3
info:
  title: Room Service v1
  description: |-
    API for Room Service
  termsOfService: http://swagger.io/terms/
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
paths:
components:
  schemas:
    ReserveRoomCommand:
      type: object
      properties:
        appointmentId:
          type: integer
        day:
          type: string
          format: date
    ReleaseRoomCommand:
      type: object
      properties:
        appointmentId:
          type: integer
        roomId:
          type: integer
        day:
          type: string
          format: date
    RoomReservedEvent:
      type: object
      properties:
        appointmentId:
          type: integer
        day:
          type: string
          format: date
        roomAvailable:
          type: boolean
        roomId:
          type: integer
    RoomReleasedEvent:
      type: object
      properties:
        appointmentId:
          type: integer
        roomId:
          type: integer
        day:
          type: string
          format: date